module.exports = {
    products: [
      {
        _id: '1',
        name: 'Producto 1',
        category: 'Shirts',
        image: '/images/1.png',
        price: 59,
        brand: 'Hiskywin',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
      },
      {
        _id: '2',
        name: 'Producto 2',
        category: 'Shirts',
        image: '/images/2.png',
        price: 70,
        brand: 'Nike',
        rating: 5,
        numReviews: 51,
      },
      {
        _id: '3',
        name: 'Producto 3',
        category: 'Shirts',
        image: '/images/3.png',
        price: 59,
        brand: 'Adidas',
        rating: 4,
        numReviews: 45,
      },
      {
        _id: '4',
        name: 'Producto 4',
        category: 'Pants',
        image: '/images/4.png',
        price: 90,
        brand: 'Under Armour',
        rating: 2.5,
        numReviews: 198,
        countInStock: 6,
      },
      {
        _id: '5',
        name: 'Producto 5',
        category: 'Pants',
        image: '/images/5.png',
        price: 119,
        brand: 'Champion',
        rating: 3.5,
        numReviews: 89,
        countInStock: 6,
      },
      {
        _id: '6',
        name: 'Producto 6',
        category: 'Pants',
        image: '/images/6.png',
        price: 85,
        brand: 'Aelfric Eden',
        rating: 4.5,
        numReviews: 45,
        countInStock: 6,
      },
    ],
  };
  